/**
 * Download a Blob directly to the default Downloads folder without
 * triggering a "Save As" browser dialog.
 */
function downloadBlob(blob, filename) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.style.display = "none";
  document.body.appendChild(a);
  a.click();
  setTimeout(() => {
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    // Small delay ensures the browser has time to initiate the download
    // before the object URL is revoked.
  }, 150);
}

class BFile {
  constructor(file, n, url) {
    const dot_index = file.name.lastIndexOf(".");
    this.file = file;
    this.n = n;
    this.size = file.size;
    this.base_name = file.name.substr(0, dot_index);
    this.extension = file.name.substr(dot_index + 1);
    this.fx = this.fy = 0.5;
    this.is_custom_focal = false;
    this.crop_scale = 1.0;
    this.flipped = false;
    this.url = url;
    this.caption = null;        // Text generated by JoyCaption (or manually set)
    this.caption_status = null; // null | "loading" | "done" | "error"
  }

  get output_format() {
    if (config.image_format == "jpeg") {
      return { ext: "jpg", format: "image/jpeg" };
    }
    if (config.image_format == "webp") {
      return { ext: "webp", format: "image/webp" };
    }
    // Preserve format
    switch (this.extension.toLowerCase()) {
      case "png":
        return { ext: "png", format: "image/png" };
      case "jpg":
      case "jpeg":
        return { ext: this.extension, format: "image/jpeg" };
      case "webp":
        return { ext: "webp", format: "image/webp" };
    }
  }

  auto_focal(callback) {
    smartcrop
      .crop(this.image, {
        width: Math.min(this.width, this.height),
        height: Math.min(this.width, this.height),
      })
      .then(result => {
        this.fx = result.topCrop.x / this.width;
        this.fy = result.topCrop.y / this.height;
        callback(this.image);
      })
      .catch(() => {
        // If smartcrop fails (e.g. CORS or canvas security error), fall back to centre focal
        this.fx = 0.5;
        this.fy = 0.5;
        callback(this.image);
      });
  }
  read(callback) {
    loadImage(this.path, (image, data) => {
      // loadImage calls back with an Event when loading fails
      if (!image || image instanceof Event) {
        callback(null);
        return;
      }
      this.image = image;
      this.width = image.naturalWidth || image.width;
      this.height = image.naturalHeight || image.height;
      this.auto_focal(callback);
    }, { canvas: false });
  }

  get path() {
    return this.url ? this.url : this.file;
  }

  get is_jpeg() {
    return ["jpg", "jpeg"].includes(this.extension.toLowerCase());
  }

  get truncated_filename() {
    let filename = this.base_name;
    if (this.base_name.length > 20) {
      filename = this.base_name.substr(0, 15) + ".." + this.base_name.substr(this.base_name.length - 5);
    }
    return filename + "." + this.extension;
  }

  get is_supported() {
    return ["jpg", "jpeg", "png", "webp"].indexOf(this.extension.toLowerCase()) > -1;
  }

  get focal_x() {
    if (this.is_custom_focal || config.auto_focal) {
      return this.fx;
    } else {
      return parseFloat(config.focal_x);
    }
  }

  get focal_y() {
    if (this.is_custom_focal || config.auto_focal) {
      return this.fy;
    } else {
      return parseFloat(config.focal_y);
    }
  }
}

const default_parameters = {
  target_width: 1200,
  target_height: 1200,
  no_resize: false,
  auto_width: false,
  auto_height: false,
  focal_x: 0.5,
  focal_y: 0.5,
  auto_focal: true,
  image_format: "preserve",
  quality_jpeg: 92,
  quality_webp: 50,
  rename: "",
  rename_start: 0,
  quality_preset: "high"
};

class BConfig {
  constructor() {
    this.load();
  }

  load(reset = false) {
    let query_params = {};
    let url = document.location.href;
    let parts = url.substr(url.lastIndexOf("?") + 1).split("&");

    for (let p of parts) {
      if (p.indexOf("=") == -1) {
        continue;
      }
      let _tempt = p.split("=");
      query_params[_tempt[0]] = this.clean_value(_tempt[1]);
    }
    if (!reset) {
      let old_url = localStorage.getItem("url");

      if ($.isEmptyObject(query_params) && old_url) {
        history.replaceState(null, null, old_url);
        this.load(reset);
        return;
      }
    }

    for (let k in default_parameters) {
      let v = default_parameters[k];
      if (query_params.hasOwnProperty(k) && !reset) {
        v = query_params[k];
      }
      this[k] = v;

      if (k == "image_format") {
        k = "image_format_" + v;
      }

      let ele = $("#" + k);
      if (!ele.length) {
        continue;
      }
      switch ((ele.attr("type") || "").toLowerCase()) {
        case "checkbox":
        case "radio":
          ele.prop("checked", v);
          break;
        case "number":
          ele.val(parseInt(v));
          break;
        default:
          ele.val(v);
      }
    }

    this.update_focal();

    this.toggle_auto_wh("auto_width", "auto_height");
    this.toggle_auto_wh("auto_height", "auto_width");
    this.calculate_ratio();
    this.toggle_no_resize();
    this.toggle_auto_focal();

    if (reset) {
      birme.preview_visible(true);
      this.update_url();
    }
  }

  update(ele) {
    let name = ele.type == "radio" ? ele.name : ele.id;
    let value;
    if (ele.type == "checkbox") {
      value = $(ele).prop("checked");
    } else {
      value = ele.value;
    }

    if (name == "quality_preset_select") {
      value = ele.options[ele.selectedIndex].value;
    }

    this[name] = value;
    if (name == "auto_width") {
      this.toggle_auto_wh("auto_width", "auto_height");
    } else if (name == "auto_height") {
      this.toggle_auto_wh("auto_height", "auto_width");
    } else if (name == "no_resize") {
      this.toggle_no_resize();
    }

    if (["target_width", "target_height", "auto_width", "auto_height"].includes(name)) {
      if (name == "target_width") {
        this.last_edit = "width";
      } else if (name == "target_height") {
        this.last_edit = "height";
      }
      this.calculate_ratio();
    }

    this.toggle_auto_focal();
    birme.preview_visible(true);
    this.update_url();
  }

  toggle_auto_wh(key, other_key) {
    let input = $("#target" + key.substr(4));

    if (this[key]) {
      input.attr("disabled", "disabled");
    } else {
      input.removeAttr("disabled");
    }
    if (this[key] && this[other_key]) {
      $("#" + other_key).trigger("click");
    }

    if (this.auto_width || this.auto_height) {
      $("body").addClass("auto-size");
    } else {
      $("body").removeClass("auto-size");
    }
  }

  toggle_auto_focal() {
    if (this.auto_width || this.auto_height || this.no_resize) {
      $(".crop-auto, .crop-align").addClass("d-none");
    } else {
      $(".crop-auto").removeClass("d-none");
      if (this.auto_focal) {
        $(".crop-align").addClass("d-none");
      } else {
        $(".crop-align").removeClass("d-none");
      }
    }
  }

  toggle_no_resize() {
    $(".no-resize")
      .siblings()
      .each((index, s) => {
        if (this.no_resize) {
          s.classList.add("d-none");
        } else {
          s.classList.remove("d-none");
        }
      });
  }

  toggle_convert_to_jpeg() {
    for (let f of birme.files) {
      if (f.extension == "png") {
        $(".convert-to-jpeg").removeClass("d-none");
        break;
      } else {
        $(".convert-to-jpeg").addClass("d-none");
      }
    }
  }

  update_focal() {
    let n = this.focal_x / 0.5 + (this.focal_y / 0.5) * 3 + 1;
    const indicator = $(".anchor-points div:last-child");
    const anchor = $(`.anchor-points div:nth-child(${n})`);
    indicator.css({
      top: anchor.css("top"),
      left: anchor.css("left"),
    });
  }

  set_focal(ele) {
    ele = $(ele);
    const n = parseInt(ele.attr("data-n"));
    if (n == 9) {
      return;
    }
    this.focal_x = (n % 3) * 0.5;
    this.focal_y = Math.floor(n / 3) * 0.5;
    const indicator = $(".anchor-points div:last-child");
    indicator.css({ top: ele.css("top"), left: ele.css("left") });
    birme.preview_visible(true);
    this.update_url();
  }

  apply_preset(width, height) {
    this.target_width  = width;
    this.target_height = height;
    this.auto_width    = false;
    this.auto_height   = false;
    $("#target_width").val(width).removeAttr("disabled");
    $("#target_height").val(height).removeAttr("disabled");
    $("#auto_width").prop("checked", false);
    $("#auto_height").prop("checked", false);
    $("body").removeClass("auto-size");
    this.calculate_ratio();
    this.toggle_auto_focal();
    birme.preview_visible(true);
    this.update_url();
  }

  flip_preset() {
    this.apply_preset(this.target_height, this.target_width);
  }

  toggle_panel(ele) {
    $(".panel.show .options-holder").slideUp(300);
    $(".panel.show").removeClass("show");

    $(ele).parent().addClass("show");
    $(ele).next().slideDown(300);
  }

  clean_value(v) {
    v = decodeURIComponent(v);
    if (v.toLowerCase() == "true" || v.toLowerCase() == "false") {
      return v == "true";
    } else {
      return v;
    }
  }

  update_url() {
    let params = [];
    for (let k in default_parameters) {
      let v = this[k];
      if (v != default_parameters[k]) {
        params.push(k + "=" + encodeURIComponent(v));
      }
    }
    history.replaceState(null, null, "?" + params.join("&"));
    localStorage.setItem("url", document.location.search);
  }

  update_ratio() {
    let r = parseFloat($("#ratio_w").val()) / parseFloat($("#ratio_h").val());
    if (this.last_edit == "height") {
      this.target_width = Math.floor(this.target_height * r);
      $("#target_width").val(this.target_width);
    } else {
      this.target_height = Math.floor(this.target_width / r);
      $("#target_height").val(this.target_height);
    }
    this.toggle_auto_focal();
    birme.preview_visible(true);
    this.update_url();
  }

  calculate_ratio() {
    if (this.auto_width || this.auto_height) {
      $(".ratio").addClass("d-none");
      return;
    } else {
      $(".ratio").removeClass("d-none");
    }
    let w = this.target_width;
    let h = this.target_height;

    for (let i = 2; i <= Math.min(w, h); i++) {
      if (w % i == 0 && h % i == 0) {
        w /= i;
        h /= i;
        i = 1;
      }
    }
    $("#ratio_w").val(w);
    $("#ratio_h").val(h);
  }
}

class Birme {
  constructor() {
    this.files = [];
    this.files_to_add = [];
    this.file_counter = 0;
    this.selected_holder = null;
    try {
      this.masonry = new Masonry(".tiles-holder", {
        transitionDuration: 0,
      });
    } catch (e) {
      // Masonry unavailable (e.g. CDN blocked) — use a no-op fallback so
      // file loading still works; tiles appear as a plain block list instead.
      // Only appended(), layout() and remove() are called in this codebase.
      this.masonry = { appended: () => {}, layout: () => {}, remove: () => {} };
    }

    let drop_area = document.querySelector("body");
    drop_area.addEventListener("drop", e => {
      e.stopPropagation();
      e.preventDefault();
      this.add_all(e);
    });
    drop_area.addEventListener("dragover", e => {
      e.stopPropagation();
      e.preventDefault();
    });
    drop_area.addEventListener("dragenter", e => {
      e.stopPropagation();
      e.preventDefault();
    });
    document.querySelector(".tiles-holder").addEventListener("scroll", _ => this.preview_visible(false));
    window.addEventListener("resize", _ => this.preview_visible(true));
    window.addEventListener("mouseup", _ => $(document).off("mousemove"));
  }

  add_all(e) {
    this.files_to_add = [];
    let _files = e["dataTransfer"] ? e.dataTransfer.files : e.target.files;
    for (let i = 0; i < _files.length; i++) {
      let f = new BFile(_files[i], this.files.length);
      if (f.is_supported) {
        this.files.push(f);
        this.files_to_add.push(f);
      }
    }
    config.toggle_convert_to_jpeg();
    $("body").addClass("not-empty");
    this.add_one();
  }

  add_one() {
    let f = this.files_to_add.shift();
    if (!f) {
      setTimeout(() => {
        this.preview_visible(false);
      }, 500);
      return;
    }
    let ele = `
    <div class="tile">
        <div class="image-holder">
              <div class="btn-delete">x</div>
              <div class="btn-flip">↕</div>
              <canvas class="image-mask"/>
          </div>
          <p>${f.truncated_filename}</p>
      </div>`;
    $(".tiles-holder").append(ele);
    let dom_ele = document.querySelector(".tile:last-child");
    this.masonry.appended(dom_ele);
    let holder = $(dom_ele.querySelector(".image-holder"));
    f.read(img => {
      if (img) holder.append(img);
      this.add_one();
    });
    holder.data("file", f);
    holder.on("mousedown", this._image_mousedown);
    holder.on("mousemove", this._image_cursor_update);
    holder.children(".btn-delete").on("click", this.remove_one);
    holder.children(".btn-flip").on("click", this.flip_one);
    this.masonry.layout();
  }

  remove_one(event) {
    let holder = $(event.target).closest(".image-holder");
    for (let i = 0; i < birme.files.length; i++) {
      if (birme.files[i] == holder.data("file")) {
        birme.files.splice(i, 1);
        break;
      }
    }
    birme.masonry.remove(holder.parent().get(0));
    $(holder).parent().detach();
    if (birme.files.length == 0) {
      $("body").removeClass("not-empty");
    } else {
      birme.masonry.layout();
    }
  }

  flip_one(event) {
    const holder = $(event.target).closest(".image-holder");
    const file = holder.data("file");
    file.flipped = !file.flipped;
    holder.children(".btn-flip").toggleClass("flipped", file.flipped);
    birme.preview_one(holder.closest(".tile")[0], file, true);
  }

  preview_visible(force_update = false) {
    this.masonry.layout();
    let tiles = document.querySelectorAll(".tile");
    let holder = document.querySelector(".tiles-holder");
    for (let i = 0; i < tiles.length; i++) {
      if (tiles[i].offsetTop + tiles[i].offsetHeight - holder.scrollTop > 0 && tiles[i].offsetTop - holder.scrollTop < holder.offsetHeight) {
        this.preview_one(tiles[i], this.files[i], force_update);
      }
    }
  }

  preview_one(holder, file, force_update) {
    const mask = holder.querySelector(".image-mask");
    if (!force_update && mask.getAttribute("width") > 0) {
      return;
    }
    var img = holder.querySelector("img");
    const tw = file.flipped ? config.target_height : config.target_width;
    const th = file.flipped ? config.target_width : config.target_height;
    const fx = file.focal_x;
    const fy = file.focal_y;
    const w = img.offsetWidth;
    const h = img.offsetHeight;
    let nw = w;
    let nh = h;
    const baseFactor = Math.min(w / tw, h / th);
    const base_nw = tw * baseFactor;
    const base_nh = th * baseFactor;
    if (!(config.auto_width || config.auto_height || config.no_resize)) {
      const cropScale = file.crop_scale || 1.0;
      nw = base_nw * cropScale;
      nh = base_nh * cropScale;
    }

    // Store crop dimensions on the image-holder for use in drag calculations
    const imageHolder = holder.classList.contains("image-holder") ? holder : holder.querySelector(".image-holder");
    $(imageHolder).data("nw", nw);
    $(imageHolder).data("nh", nh);
    $(imageHolder).data("img_w", w);
    $(imageHolder).data("img_h", h);
    $(imageHolder).data("base_nw", base_nw);
    $(imageHolder).data("base_nh", base_nh);

    mask.width = w;
    mask.height = h;

    const ctx = mask.getContext("2d");

    // Draw semi-transparent dark overlay over the entire image
    ctx.fillStyle = "rgba(0, 0, 0, 0.5)";
    ctx.fillRect(0, 0, w, h);

    // Clear the crop selection area so the underlying image shows through
    const cropX = Math.round((w - nw) * fx);
    const cropY = Math.round((h - nh) * fy);
    ctx.clearRect(cropX, cropY, nw, nh);

    // Draw a visible border around the crop selection
    ctx.strokeStyle = "rgba(255, 255, 255, 0.9)";
    ctx.lineWidth = 2;
    ctx.strokeRect(cropX, cropY, nw, nh);

    // Draw corner handles to indicate the selection is draggable
    const handleSize = 8;
    ctx.fillStyle = "rgba(255, 255, 255, 0.9)";
    ctx.fillRect(cropX, cropY, handleSize, handleSize);
    ctx.fillRect(cropX + nw - handleSize, cropY, handleSize, handleSize);
    ctx.fillRect(cropX, cropY + nh - handleSize, handleSize, handleSize);
    ctx.fillRect(cropX + nw - handleSize, cropY + nh - handleSize, handleSize, handleSize);
  }

  save_all(output_zip) {
    this.show_modal("loading");
    this.output_zip = output_zip;
    // if (this.files.length == 1) {
    // this.output_zip = false;
    // }
    this.zip = new JSZip();
    this.files_to_save = this.files.slice(0);
    this.save_one();
  }

  save_zip(b, filename, file = null) {
    this.zip.file(filename, b, {
      base64: true,
    });
    if (file && file.caption && $("#joycaption_include").prop("checked")) {
      const txt_name = filename.replace(/\.[^.]+$/, "") + ".txt";
      this.zip.file(txt_name, file.caption);
    }
    if (this.files_to_save.length == 0) {
      let w = config.auto_width ? "auto" : config.target_width;
      let h = config.auto_height ? "auto" : config.target_height;
      this.zip
        .generateAsync({
          type: "blob",
        })
        .then(content => {
          saveAs(content, `birme-${w}x${h}.zip`);
          this.hide_modal();
        });
    } else {
      this.save_one();
    }
  }

  save_one() {
    if (this.files_to_save.length == 0) {
      this.hide_modal();
      return;
    }
    let f = this.files_to_save.shift();
    loadImage(f.path, img => this.process_image(img, f), { orientation: 1 });
  }

  process_image(img, file) {
    let tw = file.flipped ? config.target_height : config.target_width;
    let th = file.flipped ? config.target_width : config.target_height;

    const fx = file.focal_x;
    const fy = file.focal_y;

    const iw = img.width;
    const ih = img.height;

    if (config.no_resize) {
      tw = file.width;
      th = file.height;
    } else if (config.auto_width) {
      tw = (img.width * th) / ih;
    } else if (config.auto_height) {
      th = (img.height * tw) / iw;
    }

    let scale = Math.min(iw / tw, ih / th) * (file.crop_scale || 1.0);
    let srcw = tw * scale;
    let srch = th * scale;

    let smoothingEnabled = true;
    let smoothingQuality = "high";

    switch (config.quality_preset) {
      case "low":
      case "medium":
      case "high":
        smoothingEnabled = true;
        smoothingQuality = config.quality_preset;
        break;
      case "disabled":
        smoothingEnabled = false;
        break;
      case "hermite":
        smoothingEnabled = false;
        break;
      default:
        console.error(`FATAL ERROR: Unexpected quality_preset=${config.quality_preset}, try re-selecting your chosen downscale quality preset in settings!`);
        throw Error(`FATAL ERROR: Unexpected quality_preset=${config.quality_preset} :(`);
    }

    // TODO: SUPPORT JPEG/WEBP QUALITY AND BORDER WIDTH SETTING
    if (config.quality_preset == "hermite") {
      let canvasHermite = document.createElement("canvas");
      let ctxHermite = canvasHermite.getContext("2d");
  
      //prepare canvas
      canvasHermite.width = srcw;
      canvasHermite.height = srch;
      
      //crop image based on focal selection (at full resolution)
      ctxHermite.drawImage(img, (iw - srcw) * fx, (ih - srch) * fy, srcw, srch, 0, 0, srcw, srch);
  
      // Use Hermite library for image downscaling
      var HERMITE = new Hermite_class();
      HERMITE.resample_single(canvasHermite, tw, th, true);

      const new_filename = file.base_name + "." + file.output_format.ext;
      if (this.output_zip) {
        canvasHermite.toBlob(b => this.save_zip(b, new_filename, file), file.output_format.format);
      } else {
        canvasHermite.toBlob(
          b => {
            downloadBlob(b, new_filename);
            if (file.caption && $("#joycaption_include").prop("checked")) {
              downloadBlob(new Blob([file.caption], { type: "text/plain" }), file.base_name + ".txt");
            }
            this.save_one();
          },
          file.output_format.format
        );
      }
      return;
    }

    let canvas = document.createElement("canvas");
    canvas.width = tw;
    canvas.height = th;
    let con = canvas.getContext("2d");

    // UTILIZE SEMI-SMART IMAGE DOWNSAMPLING
    con.imageSmoothingEnabled = smoothingEnabled;
    con.imageSmoothingQuality = smoothingQuality;

    let output = file.output_format;
    // Draw a white background for transparent images
    if (output.format == "image/jpeg" && !file.is_jpeg) {
      con.fillStyle = "white";
      con.fillRect(0, 0, tw, th);
    }
    con.drawImage(img, (iw - srcw) * fx, (ih - srch) * fy, srcw, srch,
                       0, 0, tw, th);
    let new_filename;
    if (config.rename) {
      if (config.rename.indexOf('ORIGINAL-NAME') > -1) {
        new_filename = config.rename.replace('ORIGINAL-NAME', file.base_name);
        if (new_filename.toLowerCase().indexOf('.' + output.ext) == -1) new_filename += '.' + output.ext;
      } else {
        let filename = config.rename.toLowerCase();
        var pattern = new RegExp("x{2,}");
        var result = pattern.exec(filename);
        if (!result) {
          pattern = new RegExp("x+");
          result = pattern.exec(filename);
        }
        if (!result) {
          alert('Sorry the filename pattern cannot be recognized.\nPlease try something like "image-xxx".');
          return;
        }
        let front = filename.substr(0, result.index);
        let end = filename.substr(result.index + result[0].length);
        let index = config.rename_start + "";
        config.rename_start++;
        new_filename = front + index.padStart(result[0].length, "0") + end;
        new_filename = new_filename.replace(/(\.jpe?g)|(\.png)/i, "");
        new_filename += "." + output.ext;
        config.update_url();
        $("#rename_start").val(config.rename_start);
      }
    } else {
      new_filename = file.base_name + "." + output.ext;
    }

    let quality = 92;
    if (output.format == "image/jpeg") {
      quality = config.quality_jpeg / 100;
    } else if (output.format == "image/webp") {
      quality = config.quality_webp / 100;
    } else if (output.format == "image/png") {
      quality = -1;
    }
    if (this.output_zip) {
      if (quality > 0) {
        canvas.toBlob(b => this.save_zip(b, new_filename, file), output.format, quality);
      } else {
        canvas.toBlob(b => this.save_zip(b, new_filename, file), output.format);
      }
    } else {
      if (quality > 0) {
        canvas.toBlob(
          b => {
            downloadBlob(b, new_filename);
            if (file.caption && $("#joycaption_include").prop("checked")) {
              downloadBlob(new Blob([file.caption], { type: "text/plain" }), file.base_name + ".txt");
            }
            this.save_one();
          },
          output.format,
          quality
        );
      } else {
        canvas.toBlob(
          b => {
            downloadBlob(b, new_filename);
            if (file.caption && $("#joycaption_include").prop("checked")) {
              downloadBlob(new Blob([file.caption], { type: "text/plain" }), file.base_name + ".txt");
            }
            this.save_one();
          },
          output.format
        );
      }
    }
  }

  show_section(section, jump = false) {
    let ty = $(".section-" + section).offset().top - $("nav").height() - 13;
    if (jump) {
      $("html,body").scrollTop(ty);
    } else {
      $("html,body").animate({
        scrollTop: ty,
      });
    }
  }
  show_modal(name) {
    $(".modal").addClass("show-" + name);
  }
  hide_modal() {
    $(".modal").removeClass("show-loading");
  }

  _detect_corner(holder, clientX, clientY) {
    const nw = holder.data("nw") || holder.width();
    const nh = holder.data("nh") || holder.height();
    const imgW = holder.data("img_w") || holder.width();
    const imgH = holder.data("img_h") || holder.height();
    const file = holder.data("file");
    const fx = file.focal_x;
    const fy = file.focal_y;

    const cropX = (imgW - nw) * fx;
    const cropY = (imgH - nh) * fy;

    const holderRect = holder.get(0).getBoundingClientRect();
    const scaleX = imgW / holderRect.width;
    const scaleY = imgH / holderRect.height;
    const mouseX = (clientX - holderRect.left) * scaleX;
    const mouseY = (clientY - holderRect.top) * scaleY;

    const hitSize = 16;
    if (Math.abs(mouseX - cropX) <= hitSize && Math.abs(mouseY - cropY) <= hitSize) return "tl";
    if (Math.abs(mouseX - (cropX + nw)) <= hitSize && Math.abs(mouseY - cropY) <= hitSize) return "tr";
    if (Math.abs(mouseX - cropX) <= hitSize && Math.abs(mouseY - (cropY + nh)) <= hitSize) return "bl";
    if (Math.abs(mouseX - (cropX + nw)) <= hitSize && Math.abs(mouseY - (cropY + nh)) <= hitSize) return "br";
    return null;
  }

  _image_cursor_update(event) {
    if (config.auto_width || config.auto_height) return;
    const holder = $(event.currentTarget);
    const corner = birme._detect_corner(holder, event.clientX, event.clientY);
    if (corner === "tl" || corner === "br") {
      holder.css("cursor", "nwse-resize");
    } else if (corner === "tr" || corner === "bl") {
      holder.css("cursor", "nesw-resize");
    } else {
      holder.css("cursor", "move");
    }
  }

  _image_mousedown(event) {
    if (config.auto_width || config.auto_height) return;
    let holder = $(event.originalEvent.target);
    if (!holder.hasClass("image-holder")) {
      holder = holder.closest(".image-holder");
    }
    let file = holder.data("file");

    const corner = birme._detect_corner(holder, event.clientX, event.clientY);
    holder.data("corner", corner);
    holder.data("x", event.clientX);
    holder.data("y", event.clientY);
    holder.data("fx", file.focal_x);
    holder.data("fy", file.focal_y);

    const nw = holder.data("nw") || holder.width();
    const nh = holder.data("nh") || holder.height();
    const imgW = holder.data("img_w") || holder.width();
    const imgH = holder.data("img_h") || holder.height();

    if (!corner) {
      // Pan mode: store available drag range so crop box follows mouse precisely
      holder.data("avail_w", imgW - nw);
      holder.data("avail_h", imgH - nh);
    } else {
      // Resize mode: store the anchor corner (diagonally opposite to the dragged corner)
      const cropX = (imgW - nw) * file.focal_x;
      const cropY = (imgH - nh) * file.focal_y;
      const anchorX = corner.includes("l") ? cropX + nw : cropX;
      const anchorY = corner.includes("t") ? cropY + nh : cropY;
      holder.data("anchor_x", anchorX);
      holder.data("anchor_y", anchorY);
    }

    birme.selected_holder = holder;
    $(document).off("mousemove");
    $(document).on("mousemove", birme._image_mousemove);
  }

  _image_mousemove(event) {
    let holder = birme.selected_holder;
    let file = holder.data("file");
    const corner = holder.data("corner");

    if (!corner) {
      // Pan mode: move the crop box
      const dx = event.clientX - holder.data("x");
      const dy = event.clientY - holder.data("y");

      const fx = holder.data("fx");
      const fy = holder.data("fy");

      const availW = holder.data("avail_w");
      const availH = holder.data("avail_h");

      // When the crop fills the full dimension there is no room to drag, so centre it
      const new_fx = availW > 0 ? Math.max(0, Math.min(1, fx + dx / availW)) : 0.5;
      const new_fy = availH > 0 ? Math.max(0, Math.min(1, fy + dy / availH)) : 0.5;

      file.fx = new_fx;
      file.fy = new_fy;
      file.is_custom_focal = true;

      if (new_fx !== fx || new_fy !== fy) {
        birme.preview_one(holder.get(0), file, true);
      }
    } else {
      // Resize mode: change the crop box size while maintaining aspect ratio
      const imgW = holder.data("img_w");
      const imgH = holder.data("img_h");
      const base_nw = holder.data("base_nw");
      const base_nh = holder.data("base_nh");
      const anchorX = holder.data("anchor_x");
      const anchorY = holder.data("anchor_y");

      const holderRect = holder.get(0).getBoundingClientRect();
      const scaleX = imgW / holderRect.width;
      const scaleY = imgH / holderRect.height;
      const mouseX = (event.clientX - holderRect.left) * scaleX;
      const mouseY = (event.clientY - holderRect.top) * scaleY;

      const tw = config.target_width;
      const th = config.target_height;
      const aspect = tw / th;

      // Raw size from anchor to mouse position
      let rawW = Math.abs(mouseX - anchorX);
      let rawH = Math.abs(mouseY - anchorY);

      // Maintain target aspect ratio
      if (rawW / aspect >= rawH) {
        rawH = rawW / aspect;
      } else {
        rawW = rawH * aspect;
      }

      // Constrain so the crop stays within the image bounds from the anchor
      const maxFromAnchorW = corner.includes("l") ? anchorX : imgW - anchorX;
      const maxFromAnchorH = corner.includes("t") ? anchorY : imgH - anchorY;
      rawW = Math.max(20, Math.min(rawW, maxFromAnchorW, maxFromAnchorH * aspect));
      rawH = rawW / aspect;

      // Crop box top-left from anchor + corner direction
      const cropX = corner.includes("l") ? anchorX - rawW : anchorX;
      const cropY = corner.includes("t") ? anchorY - rawH : anchorY;

      // Derive new crop_scale and focal point
      const new_crop_scale = Math.max(0.01, Math.min(1.0, rawW / base_nw));
      const actual_nw = base_nw * new_crop_scale;
      const actual_nh = base_nh * new_crop_scale;
      const avail_w = imgW - actual_nw;
      const avail_h = imgH - actual_nh;

      const new_fx = avail_w > 0 ? Math.max(0, Math.min(1, cropX / avail_w)) : 0.5;
      const new_fy = avail_h > 0 ? Math.max(0, Math.min(1, cropY / avail_h)) : 0.5;

      file.crop_scale = new_crop_scale;
      file.fx = new_fx;
      file.fy = new_fy;
      file.is_custom_focal = true;

      birme.preview_one(holder.get(0), file, true);
    }
  }

  _get_holder_index(holder) {
    let holders = $(".image-holder");
    for (let i = 0; i < holders.length; i++) {
      if (holders[i] == holder) {
        return i;
      }
    }
    return -1;
  }

  _add_test_image(n, ext) {
    var f = new BFile(new File([""], `test-image-${n}.${ext}`), this.files.length, `http://${document.location.host}/static/images/test/${n}.${ext}`);
    this.files.push(f);
    this.files_to_add.push(f);
    this.add_one();
  }

  // ── JoyCaption helpers ──────────────────────────────────────────────────

  /** Build the cropped canvas for a file (same geometry as process_image). */
  _make_crop_canvas(file) {
    const img = file.image;
    if (!img) return null;
    const tw = config.target_width;
    const th = config.target_height;
    const fx = file.focal_x;
    const fy = file.focal_y;
    const iw = img.naturalWidth  || img.width;
    const ih = img.naturalHeight || img.height;
    const scale = Math.min(iw / tw, ih / th) * (file.crop_scale || 1.0);
    const srcw  = tw * scale;
    const srch  = th * scale;
    const canvas = document.createElement("canvas");
    canvas.width  = tw;
    canvas.height = th;
    const con = canvas.getContext("2d");
    con.imageSmoothingEnabled = true;
    con.imageSmoothingQuality = "high";
    con.drawImage(img, (iw - srcw) * fx, (ih - srch) * fy, srcw, srch, 0, 0, tw, th);
    return canvas;
  }

  /** Find the .tile DOM element that owns the given BFile. */
  _find_tile(file) {
    const holders = document.querySelectorAll(".image-holder");
    for (let h of holders) {
      if ($(h).data("file") === file) {
        return h.closest(".tile");
      }
    }
    return null;
  }

  /** Refresh the caption badge on the tile for the given file. */
  _update_tile_caption(file) {
    const tile = this._find_tile(file);
    if (!tile) return;
    let badge = tile.querySelector(".caption-badge");
    if (!badge) {
      badge = document.createElement("div");
      badge.className = "caption-badge";
      tile.appendChild(badge);
    }
    if (file.caption_status === "loading") {
      badge.textContent = "⏳";
      badge.title = "Generating caption…";
    } else if (file.caption_status === "done") {
      badge.textContent = "✓";
      badge.title = file.caption;
    } else if (file.caption_status === "error") {
      badge.textContent = "✗";
      badge.title = "Captioning failed";
    } else {
      badge.remove();
    }
  }

  /**
   * Full GO workflow:
   *   1. Trigger model pre-loading via /api/preload
   *   2. Poll /api/status until the model is ready
   *   3. Caption every image using the current crop settings
   *   4. Save all cropped images + .txt caption files as a ZIP
   */
  async go_all() {
    if (this.files.length === 0) return;

    const caption_type  = document.getElementById("joycaption_type").value;
    const system_prompt = (document.getElementById("joycaption_system_prompt").value || "").trim();
    const btn    = document.getElementById("joycaption-btn");
    const status = document.getElementById("joycaption-status");

    btn.disabled = true;
    try {
      // ── Step 1: trigger model pre-loading ────────────────────────────────
      status.textContent = "Checking model…";
      try {
        await fetch("/api/preload", { method: "POST" });
      } catch (err) {
        console.debug("Preload request failed (server may not support it yet):", err.message);
      }

      // ── Step 2: poll until ready ──────────────────────────────────────────
      const POLL_INTERVAL_MS = 3000;
      const MAX_WAIT_MS      = 15 * 60 * 1000; // 15 minutes
      const deadline         = Date.now() + MAX_WAIT_MS;
      let   modelReady       = false;

      while (!modelReady) {
        if (Date.now() > deadline) throw new Error("Model loading timed out (15 min)");

        let mstatus;
        try {
          const r = await fetch("/api/status");
          const d = await r.json();
          mstatus = d.model_status;
        } catch (err) {
          throw new Error(`Cannot reach server — is it running? (${err.message})`);
        }

        if (mstatus === "ready") {
          modelReady = true;
        } else if (mstatus && mstatus.startsWith("error:")) {
          throw new Error(mstatus);
        } else {
          // "not_loaded" or "loading"
          if (mstatus === "not_loaded") {
            try { await fetch("/api/preload", { method: "POST" }); } catch (_) {}
            status.textContent = "Downloading model — this may take a few minutes…";
          } else {
            status.textContent = "Model loading — this may take a few minutes…";
          }
          await new Promise(r => setTimeout(r, POLL_INTERVAL_MS));
        }
      }

      // ── Step 3: caption all images ────────────────────────────────────────
      const total = this.files.length;
      let captioned = 0;
      let failed    = 0;

      for (let i = 0; i < this.files.length; i++) {
        const f = this.files[i];
        f.caption_status = "loading";
        this._update_tile_caption(f);
        status.textContent = `Captioning ${i + 1} / ${total}…`;

        try {
          const canvas  = this._make_crop_canvas(f);
          const dataUrl = canvas ? canvas.toDataURL("image/jpeg", 0.85) : null;
          if (!dataUrl) throw new Error("Image not loaded");

          const resp = await fetch("/api/caption", {
            method:  "POST",
            headers: { "Content-Type": "application/json" },
            body:    JSON.stringify({ image: dataUrl, caption_type, system_prompt: system_prompt || undefined }),
          });
          if (!resp.ok) throw new Error(`HTTP ${resp.status}`);
          const data = await resp.json();
          if (data.error) throw new Error(data.error);

          f.caption        = data.caption;
          f.caption_status = "done";
          captioned++;
        } catch (err) {
          f.caption_status = "error";
          failed++;
          console.error("Caption error for", f.base_name, ":", err);
        }
        this._update_tile_caption(f);
      }

      // ── Step 4: save cropped images + .txt files as ZIP ───────────────────
      const summary = `Captioned ${captioned}${failed ? `, ${failed} failed` : ""} — saving ZIP…`;
      status.textContent = summary;
      // Ensure captions are written into the archive
      document.getElementById("joycaption_include").checked = true;
      this.save_all(true);

    } catch (err) {
      status.textContent = `Error: ${err.message}`;
    } finally {
      btn.disabled = false;
    }
  }

  /** Caption all loaded images in sequence, updating the status line. */
  async caption_all() {
    if (this.files.length === 0) return;

    const caption_type  = document.getElementById("joycaption_type").value;
    const system_prompt = (document.getElementById("joycaption_system_prompt").value || "").trim();
    const btn    = document.getElementById("joycaption-btn");
    const status = document.getElementById("joycaption-status");

    btn.disabled = true;
    let done = 0;
    const total = this.files.length;

    for (let f of this.files) {
      f.caption_status = "loading";
      this._update_tile_caption(f);
      status.textContent = `Captioning ${done + 1} / ${total}…`;

      try {
        const canvas  = this._make_crop_canvas(f);
        const dataUrl = canvas ? canvas.toDataURL("image/jpeg", 0.85) : null;
        if (!dataUrl) throw new Error("Image not loaded yet");

        const resp = await fetch("/api/caption", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ image: dataUrl, caption_type, system_prompt: system_prompt || undefined }),
        });

        if (!resp.ok) throw new Error(`HTTP ${resp.status}`);
        const data = await resp.json();
        if (data.error) throw new Error(data.error);

        f.caption        = data.caption;
        f.caption_status = "done";
      } catch (err) {
        f.caption_status = "error";
        console.error("JoyCaption error:", err);
      }

      done++;
      this._update_tile_caption(f);
    }

    const ok  = this.files.filter(f => f.caption_status === "done").length;
    const err = this.files.filter(f => f.caption_status === "error").length;
    status.textContent = `Done — ${ok} captioned${err ? `, ${err} failed` : ""}`;
    btn.disabled = false;
  }

  /** Probe the /api/status endpoint and update the JoyCaption status line. */
  async _check_joycaption_status() {
    const status = document.getElementById("joycaption-status");
    const btn    = document.getElementById("joycaption-btn");
    try {
      const resp = await fetch("/api/status");
      if (!resp.ok) throw new Error("not ok");
      const data = await resp.json();
      if (data.model_status === "ready") {
        status.textContent = "Model ready";
      } else if (data.model_status === "loading") {
        status.textContent = "Model loading…";
      } else {
        status.textContent = "Server ready — model will load on first use";
      }
      btn.disabled = false;
    } catch (err) {
      console.debug("JoyCaption server not available:", err.message);
      status.textContent = "JoyCaption unavailable (open via Pinokio to enable)";
      btn.disabled = true;
    }
  }
}

let birme = new Birme();
let config = new BConfig();

// Check JoyCaption server availability on startup
birme._check_joycaption_status();

// Build the anchor-points focal grid dynamically
(function buildAnchorPoints() {
  const container = document.querySelector(".anchor-points");
  if (!container) return;
  // 9 clickable positions + 1 indicator div (last child)
  for (let n = 0; n < 10; n++) {
    const div = document.createElement("div");
    if (n < 9) {
      div.setAttribute("data-n", n);
      div.addEventListener("click", () => config.set_focal(div));
    }
    container.appendChild(div);
  }
  config.update_focal();
})();

// Testing code
if (document.location.href.indexOf("8080") > -1) {
  for (var i = 0; i < 1; i++) {
    birme._add_test_image(i + 1, "jpg");
    // birme._add_test_image(i, "webp");
  }
  // birme._add_test_image("2", "png");
  $("body").addClass("not-empty");
  // birme.show_modal("loading");
}
